version: "3"

services:
  mongo_db:
    container_name: database
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db

  server:
    build: ./server
    container_name: server
    image: numer_server_image
    ports:
      - 3000:3000
    environment:
      SEVER_PORT: 3000
      MONGO_URL: mongodb://mongo_db:27017/Numerical
    depends_on:
      - mongo_db

  client:
    build: ./swk
    container_name: client
    image: numer_client_image
    ports:
      - 5174:5173
    environment:
      VITE_API_KEYS: http://localhost:3000/api/getdata
      VITE_API_KEYS_TEST: http://localhost:3000/api/getdata
      VITE_API_KEYS_POST: http://localhost:3000/api/test
    depends_on:
      - server

volumes:
  mongo_db: {}